var cars = [
  {
    car_img: "../img/cars/ChevySilverado.svg",
    car_model: "Chevy Silverado 4500HD",
    car_style: "Mid-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/NissanRogue.svg",
    car_model: "Nissan Rogue",
    car_style: "Mid-size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/MercSprinter.svg",
    car_model: "Mercedes Benz Sprinter",
    car_style: "Mid-Size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/FordTransitlessPess.svg",
    car_model: "12-Passenger Ford Transit",
    car_style: "Mid-Size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/ChryslerPacifica.svg",
    car_model: "Chrysler Pacifica",
    car_style: "Full-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/NissanAltima.svg",
    car_model: "Nissan Altima",
    car_style: "Full-size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/FordTransitDark.svg",
    car_model: "15-Passenger Ford Transit",
    car_style: "Full-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/MercedesSclass.svg",
    car_model: "Mercedes s class",
    car_style: "Full-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Sports_cars",
  },
  {
    car_img: "../img/cars/RollsRoyceGhost.svg",
    car_model: "Royce rolls ghost",
    car_style: "Full-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Sports_cars",
  },
  {
    car_img: "../img/cars/FordTransit.svg",
    car_model: "15-Passenger Ford Transit",
    car_style: "Mid-Size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Vans",
  },
  {
    car_img: "../img/cars/MercedesG63.svg",
    car_model: "Mercedes g63 amg",
    car_style: "Mid-Size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Sports_cars",
  },
  {
    car_img: "../img/cars/FordFiesta.svg",
    car_model: "Ford Fiesta",
    car_style: "Economy Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/NissanVersa.svg",
    car_model: "Nissan Versa",
    car_style: "Compact Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/ToyotaCorolla.svg",
    car_model: "Toyota Corolla",
    car_style: "Mid-size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/ChevyTraverse.svg",
    car_model: "Chevy Traverse",
    car_style: "Full-size SUV",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Compact",
  },
  {
    car_img: "../img/cars/LomboUrus.svg",
    car_model: "Lamborghini urus",
    car_style: "Mid-Size Car",
    seat_num: 5,
    year_num: "21+",
    automatic: "automatic",
    lit_num: "2.5 km",
    car_type: "Sports_cars",
  },
];